clientes/urls.py
from django.urls import path
from clientes.views import clientes, cadastro_cliente, get_cidades, get_bairros, cadastro_estado,cadastro_cidade, cadastro_bairro, editar_cliente
from clientes.views import cadastro_propriedade, detalhar_cliente,detalhar_estado,detalhar_cidade,detalhar_bairro,editar_estado,editar_cidade,editar_bairro
from clientes.views import estados, cidades, bairros,gerenciar_endereco
urlpatterns = [
        path('clientes/', clientes, name='clientes'),
        path('estados/', estados, name='estados'),
        path('cidades/', cidades, name='cidades'),
        path('bairros/', bairros, name='bairros'),
        path('cadastro_cliente', cadastro_cliente, name='cadastro_cliente'),
        path('cadastro_propriedade/<int:cliente_id>', cadastro_propriedade, name='cadastro_propriedade'),
        path('ajax/get_cidades/', get_cidades, name='get_cidades'),
        path('ajax/get_bairros/', get_bairros, name='get_bairros'),
        path('cadastro_estado/', cadastro_estado, name='cadastro_estado'),
        path('cadastro_cidade/', cadastro_cidade, name='cadastro_cidade'),
        path('cadastro_bairro/', cadastro_bairro, name='cadastro_bairro'),
        path('editar_cliente/<int:cliente_id>', editar_cliente, name='editar_cliente'),
        path('editar_estado/<int:estado_id>', editar_estado, name='editar_estado'),
        path('editar_cidade/<int:cidade_id>', editar_cidade, name='editar_cidade'),
        path('editar_bairro/<int:bairro_id>', editar_bairro, name='editar_bairro'),
        path('detalhar_cliente/<int:cliente_id>', detalhar_cliente, name='detalhar_cliente'),
        path('detalhar_estado/<int:estado_id>', detalhar_estado, name='detalhar_estado'),
        path('detalhar_cidade/<int:cidade_id>', detalhar_cidade, name='detalhar_cidade'),
        path('detalhar_bairro/<int:bairro_id>', detalhar_bairro, name='detalhar_bairro'),
        path('gerenciar_endereco/', gerenciar_endereco, name='gerenciar_endereco'),


]

setup/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('usuarios.urls')),
    path('', include('clientes.urls')),
    path('', include('usinas.urls')),
    path('chaining/', include('smart_selects.urls')),
]

clientes/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator, EmailValidator, MinLengthValidator
from smart_selects.db_fields import ChainedForeignKey

class Estado(models.Model):
    nome = models.CharField(max_length=50, unique=True)
    sigla = models.CharField(max_length=2, unique=True)

    def __str__(self):
        return f"{self.nome} ({self.sigla})"
class Cidade(models.Model):
    nome = models.CharField(max_length=100)
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nome} - {self.estado.sigla}"

class Bairro(models.Model):
    nome = models.CharField(max_length=100)
    cidade = models.ForeignKey(Cidade, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.nome}"

class Cliente(models.Model):
    nome_completo = models.CharField(max_length=100, blank=False, null=False)
    rua = models.CharField(max_length=100, blank=False, null=False)
    numero = models.IntegerField(blank=False, null=False)
    estado = models.ForeignKey(Estado, on_delete=models.SET_NULL, blank=False, null=True)
    cidade = ChainedForeignKey(Cidade, on_delete=models.SET_NULL, blank=False, null=True,
                                        chained_field="estado",
                                        chained_model_field="estado",
                                        show_all=False,
                                        auto_choose=True,
                                        sort=True)
    bairro = ChainedForeignKey(Bairro, on_delete=models.SET_NULL, blank=False, null=True,
                                chained_field="cidade",
                                chained_model_field="cidade",
                                show_all=False,
                                auto_choose=True,
                                sort=True)

    cep_validator = RegexValidator(
        regex=r'^\d{5}-\d{3}$',
        message='CEP deve seguir o formato 12345-678.',
        code='invalid_cep'
    )
    cep = models.CharField(max_length=9, validators=[cep_validator], blank=False, null=False)

    ponto_referencia = models.CharField(max_length=200, blank=True, null=True)

    telefone_fixo_validator = RegexValidator(
        regex=r'^\(\d{2}\) \d{4,5}-\d{4}$',
        message='Telefone fixo deve seguir o formato (xx) xxxx-xxxx ou (xx) xxxxx-xxxx.',
        code='invalid_telefone_fixo'
    )
    telefone_fixo = models.CharField(max_length=15, validators=[telefone_fixo_validator], blank=True, null=True)

    celular_validator = RegexValidator(
        regex=r'^\(\d{2}\) \d{5}-\d{4}$',
        message='Número de celular deve seguir o formato (xx) xxxxx-xxxx.',
        code='invalid_celular'
    )
    numero_celular = models.CharField(max_length=15, validators=[celular_validator], blank=True, null=True)

    email_validator = EmailValidator(message='E-mail deve ser válido.', code='invalid_email')
    email = models.CharField(max_length=100, validators=[email_validator], blank=True, null=True)

    TIPO_CLIENTE_CHOICES = [
        ('PF', 'Pessoa Física'),
        ('PJ', 'Pessoa Jurídica'),
    ]
    tipo_cliente = models.CharField(max_length=50, choices=TIPO_CLIENTE_CHOICES, blank=False, null=False)

    cnpj_validator = RegexValidator(
        regex=r'^\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}$',
        message='CNPJ deve seguir o formato 12.345.678/9012-34.',
        code='invalid_cnpj'
    )
    cnpj = models.CharField(max_length=18, validators=[cnpj_validator], unique=True, blank=True, null=True,default=None)

    cpf_validator = RegexValidator(
        regex=r'^\d{3}\.\d{3}\.\d{3}-\d{2}$',
        message='CPF deve seguir o formato 123.456.789-01.',
        code='invalid_cpf'
    )
    cpf = models.CharField(max_length=14, validators=[cpf_validator], unique=True, blank=True, null=True,default=None)
    data_cadastro = models.DateTimeField(auto_now_add=True)

    
    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nome_completo

class Propriedade(models.Model):
    # Definindo as escolhas para o campo 'propriedade'
    PROPRIEDADE_CHOICES = [
        ('residencial', 'Residencial'),
        ('comercial', 'Comercial'),
        ('industrial', 'Industrial'),
        ('fazenda', 'Fazenda'),
    ]

    # Definindo as escolhas para o campo 'tipo_telhado'
    TIPO_TELHADO_CHOICES = [
        ('inclinado', 'Telhado Inclinado'),
        ('plano', 'Telhado Plano'),
        ('metal', 'Telhado de Metal'),
        ('estrutura elevada', 'Estrutura Elevada'),
    ]

    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, verbose_name='Cliente')
    propriedade = models.CharField(max_length=50, choices=PROPRIEDADE_CHOICES, verbose_name='Tipo de Propriedade')
    area_instalacao = models.IntegerField(verbose_name='Área de Instalação')
    consumo = models.IntegerField(verbose_name='Consumo Mensal')
    tipo_telhado = models.CharField(max_length=50, choices=TIPO_TELHADO_CHOICES, verbose_name='Tipo de Telhado')
    latitude = models.FloatField(null=True, blank=True, verbose_name='Latitude')
    longitude = models.FloatField(null=True, blank=True, verbose_name='Longitude')

    def __str__(self):
        return f"{self.get_propriedade_display()} - {self.cliente.nome_completo}"

    class Meta:
        verbose_name = 'Propriedade'
        verbose_name_plural = 'Propriedades'
    
class Rateio(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    nome = models.CharField(max_length=120)
    endereco = models.CharField(max_length=200)
    conta_contrato = models.IntegerField()

    def __str__(self):
        return f"{self.nome} - {self.cliente.nome}"

clientes/forms.py
from django import forms
from django.core.validators import RegexValidator, ValidationError, EmailValidator
from .models import Cliente, Estado, Cidade, Bairro, Propriedade


class EstadoForm(forms.ModelForm):
    class Meta:
        model = Estado
        fields = ['nome', 'sigla']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'sigla': forms.TextInput(attrs={'class': 'form-control'}),
            'origin_page': forms.HiddenInput()  # Mantendo o campo oculto como está
        }
        origin_page = forms.CharField(widget=forms.HiddenInput(), initial='cadastro_cliente')


class CidadeForm(forms.ModelForm):
    class Meta:
        model = Cidade
        fields = ['nome', 'estado']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'estado': forms.Select(attrs={'class': 'form-control'}),
            'origin_page': forms.HiddenInput()
        }
        origin_page = forms.CharField(widget=forms.HiddenInput(), initial='cadastro_cliente')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Ordena as opções de estado por nome na ordem alfabética
        self.fields['estado'].queryset = self.fields['estado'].queryset.order_by('nome')

class BairroForm(forms.ModelForm):
    class Meta:
        model = Bairro
        fields = ['nome', 'cidade']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'cidade': forms.Select(attrs={'class': 'form-control'}),
            'origin_page': forms.HiddenInput()
        }
        origin_page = forms.CharField(widget=forms.HiddenInput(), initial='cadastro_cliente')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Ordena as opções de cidade por nome na ordem alfabética
        self.fields['cidade'].queryset = self.fields['cidade'].queryset.order_by('nome')

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'  # Use '__all__' para incluir todos os campos do modelo no formulário
        widgets = {
            'nome_completo': forms.TextInput(attrs={'class': 'form-control'}),
            'rua': forms.TextInput(attrs={'class': 'form-control'}),
            'numero': forms.NumberInput(attrs={'class': 'form-control'}),
            'estado': forms.Select(attrs={'class': 'form-control'}),
            'cidade': forms.Select(attrs={'class': 'form-control'}),
            'bairro': forms.Select(attrs={'class': 'form-control'}),
            'ponto_referencia': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_cliente': forms.Select(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.fields['cep'] = forms.CharField(
            max_length=9, 
            validators=[RegexValidator(regex=r'^\d{5}-\d{3}$', message='CEP deve seguir o formato 12345-678.')],
            widget=forms.TextInput(attrs={'class': 'form-control'})
        )
        self.fields['telefone_fixo'] = forms.CharField(
            required=False, 
            validators=[RegexValidator(regex=r'^\(\d{2}\) \d{4,5}-\d{4}$',message='Telefone fixo deve seguir o formato (xx) xxxx-xxxx ou (xx) xxxxx-xxxx.')],
            widget=forms.TextInput(attrs={'class': 'form-control'})
        )

        self.fields['numero_celular'] = forms.CharField(
            required=False, 
            validators=[RegexValidator(regex=r'^\(\d{2}\) \d{5}-\d{4}$',message='Número de celular deve seguir o formato (xx) xxxxx-xxxx.')],
            widget=forms.TextInput(attrs={'class': 'form-control'})
        )

        self.fields['email'] = forms.CharField(
            required=False, 
            validators=[EmailValidator(message='E-mail deve ser válido.')],
            widget=forms.EmailInput(attrs={'class': 'form-control'})
        )

        self.fields['cnpj'] = forms.CharField(
            required=False, 
            validators=[RegexValidator(regex=r'^\d{2}\.\d{3}\.\d{3}/\d{4}-\d{2}$', message='CNPJ deve seguir o formato 12.345.678/9012-34.') ],
            widget=forms.TextInput(attrs={'class': 'form-control'}),
            initial=None  # Se você quiser definir um valor inicial
        )

        self.fields['cpf'] = forms.CharField(
            required=False, 
            validators=[RegexValidator(regex=r'^\d{3}\.\d{3}\.\d{3}-\d{2}$',message='CPF deve seguir o formato 123.456.789-01.')],
            widget=forms.TextInput(attrs={'class': 'form-control'}),
            initial=None
        )
        cidades = Cidade.objects.values_list('id', 'nome')
        bairros = Bairro.objects.values_list('id', 'nome')

        self.fields['cidade'].choices = [('', 'Escolha uma cidade')] + list(cidades)
        self.fields['bairro'].choices = [('', 'Escolha um bairro')] + list(bairros)
        self.fields['estado'].queryset = self.fields['estado'].queryset.order_by('nome')

        # Adicione aqui a lógica para imprimir as opções de Cidade e Bairro
        print('Opções de Cidade:', list(Cidade.objects.values_list('id', 'nome')))
        print('Opções de Bairro:', list(Bairro.objects.values_list('id', 'nome')))

    def clean(self):
        cleaned_data = super().clean()
        tipo_cliente = cleaned_data.get('tipo_cliente')
        cidade = cleaned_data.get('cidade')
        bairro = cleaned_data.get('bairro')

        if tipo_cliente == 'PJ' and not cleaned_data.get('cnpj'):
            raise ValidationError({'cnpj': 'CNPJ é obrigatório para Pessoa Jurídica.'})
        elif tipo_cliente == 'PF' and not cleaned_data.get('cpf'):
            raise ValidationError({'cpf': 'CPF é obrigatório para Pessoa Física.'})


    def clean_cidade(self):
        cidade = self.cleaned_data['cidade']
        if not cidade:
            raise ValidationError('Escolha uma cidade válida.')
        return cidade

    def clean_bairro(self):
        bairro = self.cleaned_data['bairro']
        if not bairro:
            raise ValidationError('Escolha um bairro válido.')
        return bairro

    def clean_cnpj(self):
        cnpj = self.cleaned_data['cnpj']
        if cnpj.strip() == '':
            return None  # Permitir CNPJ vazio
        return cnpj

    def savecnpj(self, commit=True):
        instance = super().save(commit=False)
        cnpj = self.cleaned_data['cnpj']
        if cnpj == '':
            instance.cnpj = None  # Definir como None se o campo for vazio
        if commit:
            instance.save()
        return instance

    def clean_cpf(self):
        cpf = self.cleaned_data['cpf']
        if cpf.strip() == '':
            return None  # Permitir CNPJ vazio
        return cpf

    def savecpf(self, commit=True):
        instance = super().save(commit=False)
        cpf = self.cleaned_data['cpf']
        if cpf == '':
            instance.cpf = None  # Definir como None se o campo for vazio
        if commit:
            instance.save()
        return instance

class PropriedadeForm(forms.ModelForm):
    class Meta:
        model = Propriedade
        fields = ['cliente', 'propriedade', 'area_instalacao', 'consumo', 'tipo_telhado', 'latitude', 'longitude']
        widgets = {
            'cliente': forms.Select(attrs={'class': 'form-control'}),
            'propriedade': forms.Select(attrs={'class': 'form-control'}),
            'area_instalacao': forms.NumberInput(attrs={'class': 'form-control'}),
            'consumo': forms.NumberInput(attrs={'class': 'form-control'}),
            'tipo_telhado': forms.Select(attrs={'class': 'form-control'}),
            'latitude': forms.NumberInput(attrs={'class': 'form-control'}),
            'longitude': forms.NumberInput(attrs={'class': 'form-control'}),
        }

templates/clientes/cadastro_cidade.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
          <input type="hidden" name="origin_page" value="cadastro_cidade">
        <button type="submit">Enviar</button>
  </form>

  {% endblock %}

templates/clientes/cadastro_estado.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="origin_page" value="cadastro_estado">
        <button type="submit">Enviar</button>
  </form>

  {% endblock %}

templates/clientes/cadastro_propriedade.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h2>Cadastrar Local de Instalacao</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Salvar</button>
    </form>
</div>
{% endblock %}

templates/clientes/cidades.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
{% endblock %}

templates/clientes/detalhar_bairro.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-9 offset-md-1">
            <div class="card">
                <div class="card-header">
                    Detalhes do Bairro
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Bairro:</strong> {{ bairro.nome }}</p>
                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Cidade:</strong> {{ bairro.cidade }}</p>
                            
                        </div>
                                              
                    </div>
                    <a class="btn btn-primary" href="{% url 'bairros' %}">Consultar bairros</a>
                    <a class="btn btn-primary" href="{% url 'editar_bairro' bairro.id %}">Editar</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/clientes/detalhar_cidade.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-9 offset-md-1">
            <div class="card">
                <div class="card-header">
                    Detalhes da Cidade
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Cidade:</strong> {{ cidade.nome }}</p>
                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <p><strong>Estado:</strong> {{ cidade.estado }}</p>
                            
                        </div>
                                              
                    </div>
                    <a class="btn btn-primary" href="{% url 'cidades' %}">Consultar bairros</a>
                    <a class="btn btn-primary" href="{% url 'editar_cidade' cidade.id %}">Editar</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/clientes/editar_cidade.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-9 offset-md-1">
            <div class="card">
                <div class="card-header">
                    Cadastro de Cidade
                </div>
                <div class="card-body">
                    <form method="post" id="form_cadastro_cidade" class="form-horizontal">
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-md-6">
                              <div class="form-group row">
                                  <label for="id_nome_cidade" class="col-sm-3 text-end control-label col-form-label">Nome da Cidade:</label>
                                  <div class="col-sm-9">
                                      {{ form.nome}}
                                  </div>
                              </div>
                              <div class="form-group row">
                                <label for="id_estado" class="col-sm-3 text-end control-label col-form-label">Estado:</label>
                                <div class="col-sm-9">
                                    {{ form.estado }}
                                </div>
                            </div>
                            </div>
                      <button type="submit" class="btn btn-primary">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/clientes/editar_cliente.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}

<div class="container mt-5">
  <div class="row">
      <div class="col-md-9 offset-md-1">
          <div class="card">
              <div class="card-header">
                  Edição de Cliente
              </div>
              <div class="card-body">
                  <form method="post" id="form_cadastro_cliente" class="form-horizontal">
                      {% csrf_token %}
                      <div class="row">
                    <!-- Primeira Coluna: NOME até CEP -->
                          <div class="col-md-6">
                            <div class="form-group row">
                                <label for="id_nome_completo" class="col-sm-3 text-end control-label col-form-label">Nome Completo:</label>
                                <div class="col-sm-9">
                                    {{ form.nome_completo }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_rua" class="col-sm-3 text-end control-label col-form-label">Rua:</label>
                                <div class="col-sm-9">
                                    {{ form.rua }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_numero" class="col-sm-3 text-end control-label col-form-label">Número:</label>
                                <div class="col-sm-9">
                                    {{ form.numero }}
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_estado" class="col-sm-3 text-end control-label col-form-label">Estado:</label>
                                <div class="col-sm-9">
                                    <div class="input-group">
                                        {{ form.estado }}
                                        <div class="input-group-append">
                                            <a class="btn btn-outline-secondary" id="cadastro_estado" data-popup="yes" href="cadastro_estado/?_to_field=id&amp;_popup=1" title="Adicionar outro estado">
                                                <img src="/static/admin/img/icon-addlink.svg" alt="Adicionar">Estado
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_cidade" class="col-sm-3 text-end control-label col-form-label">Cidade:</label>
                                <div class="col-sm-9">
                                    <div class="input-group">
                                        {{ form.cidade }}
                                        <div class="input-group-append">
                                            <a class="btn btn-outline-secondary" id="cadastro_cidade" data-popup="yes" href="cadastro_cidade/?_to_field=id&amp;_popup=1" title="Adicionar outra cidade">
                                                <img src="/static/admin/img/icon-addlink.svg" alt="Adicionar">Cidade
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_bairro" class="col-sm-3 text-end control-label col-form-label">Bairro:</label>
                                <div class="col-sm-9">
                                    <div class="input-group">
                                        {{ form.bairro }}
                                        <div class="input-group-append">
                                            <a class="btn btn-outline-secondary" id="cadastro_bairro" data-popup="yes" href="cadastro_bairro/?_to_field=id&amp;_popup=1" title="Adicionar outro bairro">
                                                <img src="/static/admin/img/icon-addlink.svg" alt="Adicionar">Bairro
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="id_cep" class="col-sm-3 text-end control-label col-form-label">CEP:</label>
                                <div class="col-sm-9">
                                    {{ form.cep }}
                                </div>
                            </div>
                      <div class="form-group row">
                          <label for="id_ponto_referencia" class="col-sm-3 text-end control-label col-form-label">Ponto de Referência:</label>
                          <div class="col-sm-9">
                              {{ form.ponto_referencia }}
                          </div>
                      </div>
                    </div>
                    <!-- Segunda Coluna: PONTO DE REFERÊNCIA até CPF -->
                      <div class="col-md-6">
                      <div class="form-group row">
                          <label for="id_telefone_fixo" class="col-sm-3 text-end control-label col-form-label">Telefone Fixo:</label>
                          <div class="col-sm-9">
                              {{ form.telefone_fixo }}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_numero_celular" class="col-sm-3 text-end control-label col-form-label">Celular:</label>
                          <div class="col-sm-9">
                              {{ form.numero_celular }}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_email" class="col-sm-3 text-end control-label col-form-label">Email:</label>
                          <div class="col-sm-9">
                              {{ form.email }}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_tipo_cliente" class="col-sm-3 text-end control-label col-form-label">Tipo de Cliente:</label>
                          <div class="col-sm-9">
                              {{ form.tipo_cliente }}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_cnpj" class="col-sm-3 text-end control-label col-form-label">CNPJ:</label>
                          <div class="col-sm-9">
                              {{ form.cnpj }}
                          </div>
                      </div>
                      <div class="form-group row">
                          <label for="id_cpf" class="col-sm-3 text-end control-label col-form-label">CPF:</label>
                          <div class="col-sm-9">
                              {{ form.cpf }}
                          </div>
                      </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Salvar Alterações</button>
                  </form>
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock %}

templates/clientes/estados.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
{% endblock %}

templates/clientes/novo_cliente.html
{% extends 'shared/base.html' %}
{% load static %}
{% block content %}
<form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
  </form>

    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        $(document).ready(function() {
            $('#id_estado').change(function() {
              // Limpa o campo do bairro
              $('#id_bairro').val('');
                var estadoId = $(this).val();
                console.log('Estado selecionada:', estadoId);
                if (estadoId) {
                    $.ajax({
                        url: '/ajax/get_cidades/',
                        data: {'estado_id': estadoId},
                        success: function(data) {
                          console.log('Dados recebidos:', data)
                            $('#id_cidade').empty();
                            // Adiciona a opção vazia
                            $('#id_cidade').append($('<option>', {
                            value: '',
                            text: '---------' }));
                            $.each(data, function(index, city) {
                                $('#id_cidade').append($('<option>', {
                                    value: city.id,
                                    text: city.nome
                                }));
                            });
                        }
                    });
                }
            });

            $('#id_cidade').change(function() {
                var cidadeId = $(this).val();
                console.log('Cidade selecionada:', cidadeId);
                if (cidadeId) {
                    $.ajax({
                        url: '/ajax/get_bairros/',
                        data: {'cidade_id': cidadeId},
                        success: function(data) {
                          console.log('Dados recebidos:', data)
                            $('#id_bairro').empty();
                            $('#id_bairro').append($('<option>', {
                           value: '',
                           text: '---------'
                            }));
                            $.each(data, function(index, bairro) {
                                $('#id_bairro').append($('<option>', {
                                    value: bairro.id,
                                    text: bairro.nome
                                }));
                            });
                        }
                    });
                }
            });
            $('#id_bairro').change(function() {
                var bairroId = $(this).val();
                console.log('Bairro selecionada:', bairroId);
                });
        });
    </script>

  {% endblock %}